apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    env: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
    env: prod
